package com.ap.main;

import com.ap.configuracion.Parametros;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 * Contenedor <code>JPanel</code> que se mostrará al inicio del juego, a modo
 * de presentación
 * 
 * @author Sergio
 * @version 1.0, 6 Jun 2014
 */
public final class PanelPresentacion extends javax.swing.JPanel {

    private final Main main;
    private final Musica musica;
    
    /**
     * Constructor de <code>PanelPresentacion</code>
     * @param main Frame principal del juego
     * @see Main
     */
    public PanelPresentacion(Main main) {
        this.main = main;
        //Selecciono la música
        this.musica = new Musica("grassy_world");
        
        initComponents();
        initMoreComponents();
    }
    
    /**
     * Configuración de los distintos elementos del panel.
     */
    public void initMoreComponents(){
        JLabel lbFondo = new JLabel();
        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pantalla_presentacion.png")));
        lbFondo.setBounds(0,0,640,375);
        this.add(lbFondo,new Integer(1));
        
        main.getJMenuBar().setVisible(false);
        
        JButton botonJuego = new JButton();
        botonJuego.setBounds(0,375,634,80);
        this.add(botonJuego,new Integer(1));
        
        botonJuego.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonJuego.setText("Entrar a Asgard (1.0)");
        botonJuego.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJuegoActionPerformed(evt);
            }
        });
        
        //lanzo el hilo musical
        this.musica.getHiloMusica().start();
    }
    
    /**
     * Cierra el <code>PanelPresentacion</code> e instancia un <code>PanelJuego</code>
     * para dar comienzo al juego.
     * 
     * @param evt 
     */
    private void botonJuegoActionPerformed(java.awt.event.ActionEvent evt) {   
        main.getJMenuBar().setVisible(true);
        main.setPanelJuego(new PanelJuego(musica));
        main.getPanelJuego().setBounds(
            0,
            0,
            Parametros.getInstance().getANCHO_PANTALLA_JUEGO(),
            Parametros.getInstance().getALTO_PANTALLA_JUEGO()
        );
        main.setSize(main.getWidth(), main.getHeight()+48);
        main.remove(this);
        main.add(main.getPanelJuego(),new Integer(0));
        main.getPanelJuego().requestFocus();
    } 
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
